# Generated by Django 4.1.3 on 2022-12-07 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0003_alter_contract_amount_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("POTENTIAL_CLIENT", "Client potentiel"),
                    ("EXISTING_CLIENT", "Client existant"),
                ],
                default=1,
                max_length=20,
                verbose_name="Type de client",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable de l'évènement",
            ),
        ),
    ]
